version: '3.8'

services:
  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - trading_network

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: streamlit run dashboard/app.py
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - trading_bot
      - redis
    networks:
      - trading_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - trading_network

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: trading_bot
      POSTGRES_USER: "${DB_USER:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-postgres}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trading_network

networks:
  trading_network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
